# Generated by Django 3.2.6 on 2021-10-14 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buddyAbroadAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Interests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=400, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interests', models.ForeignKey(db_column='Interests_id', on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.interests')),
            ],
            options={
                'db_table': 'user_interest',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserTrips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paidprice', models.FloatField(blank=True, db_column='paidPrice', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
                ('groupsize', models.IntegerField(blank=True, db_column='groupSize', null=True)),
                ('user_tripscol', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user_trips',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='BuddyInfo',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Preferences',
        ),
        migrations.DeleteModel(
            name='PreferencesUser',
        ),
        migrations.DeleteModel(
            name='TripsDetails',
        ),
        migrations.DeleteModel(
            name='TripsImages',
        ),
        migrations.DeleteModel(
            name='TuristInfo',
        ),
        migrations.AlterModelOptions(
            name='buddymatchtourist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='trips',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='usertrips',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='guide_id', to='buddyAbroadAPI.users'),
        ),
        migrations.AddField(
            model_name='usertrips',
            name='reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.trips'),
        ),
        migrations.AddField(
            model_name='usertrips',
            name='tourist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tourist_id', to='buddyAbroadAPI.users'),
        ),
        migrations.AddField(
            model_name='userinterest',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buddyAbroadAPI.users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='recipient',
            field=models.ForeignKey(blank=True, db_column='recipient', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recipient', to='buddyAbroadAPI.users'),
        ),
        migrations.AddField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(blank=True, db_column='sender', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='buddyAbroadAPI.users'),
        ),
        migrations.AlterUniqueTogether(
            name='messages',
            unique_together={('sender', 'recipient')},
        ),
    ]
